//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3074
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为所有资源查找重写当前线程的 CurrentUICulture 属性，
        ///   方法是使用此强类型资源类。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 about 的本地化字符串。
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 blog 的本地化字符串。
        /// </summary>
        internal static string blog {
            get {
                return ResourceManager.GetString("blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 choose language 的本地化字符串。
        /// </summary>
        internal static string choose_language {
            get {
                return ResourceManager.GetString("choose_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 close this notice 的本地化字符串。
        /// </summary>
        internal static string close_this_notice {
            get {
                return ResourceManager.GetString("close_this_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 create 的本地化字符串。
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 flanker base 的本地化字符串。
        /// </summary>
        internal static string flankerBase {
            get {
                return ResourceManager.GetString("flankerBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 for a better experience using this site, please upgrade to a modern web browser 的本地化字符串。
        /// </summary>
        internal static string for_a_better_experience_blablabla {
            get {
                return ResourceManager.GetString("for_a_better_experience_blablabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 get Firefox 3.5 的本地化字符串。
        /// </summary>
        internal static string get_Firefox {
            get {
                return ResourceManager.GetString("get_Firefox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 get Google Chrome 的本地化字符串。
        /// </summary>
        internal static string get_Google_Chrome {
            get {
                return ResourceManager.GetString("get_Google_Chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 get Internet Explorer 8 的本地化字符串。
        /// </summary>
        internal static string get_Internet_Explorer {
            get {
                return ResourceManager.GetString("get_Internet_Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 get Safari 4 的本地化字符串。
        /// </summary>
        internal static string get_Safari {
            get {
                return ResourceManager.GetString("get_Safari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 home 的本地化字符串。
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 login was unsuccessful. please correct the errors and try again. 的本地化字符串。
        /// </summary>
        internal static string login_was_unsuccessful {
            get {
                return ResourceManager.GetString("login_was_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 log off 的本地化字符串。
        /// </summary>
        internal static string logoff {
            get {
                return ResourceManager.GetString("logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 log on 的本地化字符串。
        /// </summary>
        internal static string logon {
            get {
                return ResourceManager.GetString("logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 next » 的本地化字符串。
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 password 的本地化字符串。
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 please enter your username and password 的本地化字符串。
        /// </summary>
        internal static string please_enter_your_name_and_password {
            get {
                return ResourceManager.GetString("please_enter_your_name_and_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 « previous 的本地化字符串。
        /// </summary>
        internal static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 remember me 的本地化字符串。
        /// </summary>
        internal static string remember_me {
            get {
                return ResourceManager.GetString("remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 username 的本地化字符串。
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 welcome 的本地化字符串。
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 you are using an outdated browser 的本地化字符串。
        /// </summary>
        internal static string you_are_using_an_outdated_browser {
            get {
                return ResourceManager.GetString("you_are_using_an_outdated_browser", resourceCulture);
            }
        }
    }
}
