{ 
    'wiki-url': "http://en.wikipedia.org/wiki/", 
    'wiki-section': "Pacific_War", 
    'dateTimeFormat': 'iso8601',
    'events': [
    {
        'id': '0',
        'eventID': '0',
        'start': '1941-12-07',
        'end': '1941-12-07',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Attack on Pearl Harbor',
        'location': 'Pearl Harbour, Honolulu, Hawaii',
        'lat': '21.3440326',
        'lng': '-157.9750995',
        'wiki': 'http://en.wikipedia.org/wiki/Attack_on_Pearl_Harbor',
        'description':  'The attack on Pearl Harbor (called the Hawaii Operation or Operation Z by the Japanese Imperial General Headquarters, and the Battle of Pearl Harbor by some Americans)[6] was a surprise military strike conducted by the Imperial Japanese Navy against the United States naval base at Pearl Harbor, Hawaii on the morning of December 7, 1941. The next day the United States declared war on Japan resulting in their entry into World War II. The attack was intended as a preventive action in order to keep the U.S. Pacific Fleet from influencing the war that the Empire of Japan was planning in Southeast Asia, against Britain and the Netherlands, as well as the U.S. in the Philippines. The base was attacked by Japanese aircraft (a total of 353, in two waves) launched from six aircraft carriers.[7] '
    },{
        'id': '1',
        'eventID': '1',
        'start': '1941-12-07',
        'end': '1942-05-05',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Invasion of the Philippine Islands',
        'location': 'Philippines',
        'lat': '12.879721',
        'lng': '121.774017',
        'wiki': 'http://en.wikipedia.org/wiki/Philippines_Campaign_(1941%E2%80%9342)',
        'description': 'The Philippines Campaign (1941–1942) or the Battle of the Philippines was the invasion of the Philippines by Japan in 1941–1942 and the defense of the islands by Filipino and United States forces.'
    },{
        'id': '2',
        'eventID': '2',
        'start': '1941-12-08',
        'end': '1941-12-10',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Invasion of Guam',
        'location': 'Guam, Mariana Islands',
        'lat': '13.444304',
        'lng': '144.793731',
        'wiki': 'http://en.wikipedia.org/wiki/Battle_of_Guam_(1941)',
        'description': 'The First Battle of Guam, was an engagement during the Pacific War in World War II, and took place on December 8, 1941 on Guam in the Mariana Islands between the Empire of Japan and United States forces. The American garrison was defeated by Japanese forces which resulted in an occupation until the Second Battle of Guam in 1944.'
    },{
        'id': '3',
        'eventID': '3',
        'start': '1941-12-08',
        'end': '1942-01-31',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Invasion of Malaya',
        'location': 'Malaysia',
        'lat': '4.210484',
        'lng': '101.975766',
        'wiki': 'http://en.wikipedia.org/wiki/Battle_of_Malaya',
        'description': 'The First Battle of Guam, was an engagement during the Pacific War in World War II, and took place on December 8, 1941 on Guam in the Mariana Islands between the Empire of Japan and United States forces. The American garrison was defeated by Japanese forces which resulted in an occupation until the Second Battle of Guam in 1944.'
    },{
        'id': '4',
        'eventID': '4',
        'start': '1941-12-08',
        'end': '1942-02-15',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Invasion of Singapore',
        'location': 'Singapore',
        'lat': '1.2894365',
        'lng': '103.8499802',
        'wiki': 'http://en.wikipedia.org/wiki/Battle_of_Singapore',
        'description': 'The Battle of Singapore was fought in the South-East Asian theatre of World War II when the Empire of Japan invaded the Allied stronghold of Singapore. Singapore was the major British military base in South East Asia and nicknamed the "Gibraltar of the East". The fighting in Singapore lasted from 31 January 1942 to 15 February 1942.'
    },{
        'id': '5',
        'eventID': '5',
        'start': '1941-12-08',
        'end': '1941-12-23',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Battle of Wake Island',
        'location': 'Wake Island',
        'lat': '19.2819444',
        'lng': '166.6502778',
        'wiki': 'http://en.wikipedia.org/wiki/Battle_of_Wake_Island',
        'description': 'The Battle of Wake Island began simultaneously with the Attack on Pearl Harbor and ended on December 23, 1941, with the surrender of the American forces to the Empire of Japan. It was fought on and around the atoll formed by Wake Island and its islets of Peale and Wilkes Islands by the air, land and naval forces of the Empire of Japan against those of the United States of America, with Marines playing a prominent role on both sides.'
    },{
        'id': '6',
        'eventID': '6',
        'start': '1941-12-15',
        'end': '1942-04-01',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Invasion of Borneo',
        'location': 'Borneo, Indonesia',
        'lat': '3.3546795',
        'lng': '117.5965403',
        'wiki': 'http://en.wikipedia.org/wiki/Battle_of_Borneo_(1941%E2%80%9342)',
        'description': 'The Battle of Borneo was a successful campaign by Japanese Imperial forces for control of Borneo island and concentrated mainly on the subjugation of the Kingdom of Sarawak, North Borneo, and the western part of Kalimantan that was part of the Dutch East Indies. The Japanese main unit for this mission was the 35th Infantry Brigade led by Major-General Kiyotake Kawaguchi.'
    },{
        'id': '7',
        'eventID': '7',
        'start': '1942-01-04',
        'end': '1942-01-23',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Battle of Rabaul',
        'location': 'Rabaul, Papua New Guinea',
        'lat': '-4.196161',
        'lng': '152.172962',
        'wiki': 'http://en.wikipedia.org/wiki/Battle_of_Rabaul_(1942)',
        'description': 'The Battle of Rabaul, also known by the Japanese as Operation R, was fought on the island of New Britain in the Australian Territory of New Guinea, in January and February 1942. It was a strategically significant defeat of Allied forces by Japan in the Pacific campaign of World War II. Following the capture of the port of Rabaul, Japanese forces turned it into a major base and proceeded to land on mainland New Guinea, advancing towards Port Moresby and Australia. Hostilities on the neighbouring island of New Ireland are also usually considered to be part of the same battle. Rabaul was important because of its proximity to the Japanese territory of the Caroline Islands, site of a major Imperial Japanese Navy base on Truk.'
    },{
        'id': '8',
        'eventID': '8',
        'start': '1942-02-28',
        'end': '1942-03-12',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Java Campaign',
        'location': 'Java, Indonesia',
        'lat': '-7.6145292',
        'lng': '110.7122465',
        'wiki': 'http://en.wikipedia.org/wiki/Battle_of_Java_(1942)',
        'description': 'The Battle of Java (Invasion of Java, Operation J) was a battle of the Pacific theatre of World War II. It occurred on the island of Java, between 28 February and 12 March 1942. It involved forces from the Empire of Japan, which invaded on 28 February 1942, and Allied personnel. Allied commanders signed a formal surrender at Japanese headquarters at Bandung on 12 March.'
    },{
        'id': '9',
        'eventID': '9',
        'start': '1942-02-19',
        'end': '1942-02-19',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Attack on Darwin',
        'location': 'Darwin, Australia',
        'lat': '-12.461334',
        'lng': '130.841904',
        'wiki': 'http://en.wikipedia.org/wiki/Bombing_of_Darwin',
        'description': 'The Japanese air raids on Darwin on 19 February 1942 were the largest attacks ever mounted by a foreign power against Australia. They were also a significant action in the Pacific campaign of World War II and represented a psychological blow to the Australian population, several weeks after hostilities with Japan had begun. The raids were the first of almost 100 air raids against Australia during 1942–43.'
    },{
        'id': '10',
        'eventID': '10',
        'start': '1942-04-18',
        'end': '1942-04-18',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Doolittle Raid',
        'location': 'Japan',
        'lat': '36.204824',
        'lng': '138.252924',
        'wiki': 'http://en.wikipedia.org/wiki/Doolittle_Raid',
        'description': 'The Doolittle Raid, on 18 April 1942, was the first air raid by the United States to strike the Japanese Home Islands (Honshu) during World War II. It demonstrated that Japan itself was vulnerable to American air attack, and it exploited a vital psychological need and opportunity for U.S. retaliation after the Japanese attack on Pearl Harbor on 7 December 1941. The raid was planned and led by Lieutenant Colonel James "Jimmy" Doolittle. Doolittle would later recount in his autobiography that the raid was intended to bolster American morale and to cause the Japanese to begin doubting their leadership.'
    },{
        'id': '11',
        'eventID': '11',
        'start': '1942-05-04',
        'end': '1942-05-08',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Battle of the Coral Sea',
        'location': 'Coral Sea',
        'lat': '-19.3919547',
        'lng': '155.8560646',
        'wiki': 'http://en.wikipedia.org/wiki/Battle_of_the_Coral_Sea',
        'description': 'The Battle of the Coral Sea, fought during May 4–8, 1942, was a major naval battle in the Pacific Theater of World War II between the Imperial Japanese Navy and Allied naval and air forces from the United States (U.S.) and Australia. The battle was the first fleet action in which aircraft carriers engaged each other. It was also the first naval battle in history in which neither side\'s ships sighted or fired directly upon the other.'
    },{
        'id': '12',
        'eventID': '12',
        'start': '1942-06-04',
        'end': '1942-06-07',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Battle of Midway',
        'location': 'Midway Atoll, Hawaii, Baker Island',
        'lat': '28.182595',
        'lng': '-177.384497',
        'wiki': 'http://en.wikipedia.org/wiki/Battle_of_Midway',
        'description': 'The Battle of Midway is widely regarded as the most important naval battle of the Pacific Campaign of World War II.[5][6][7] Between 4 and 7 June 1942, approximately one month after the Battle of the Coral Sea and six months after Japan\'s attack on Pearl Harbor, the United States Navy decisively defeated an Imperial Japanese Navy (IJN) attack against Midway Atoll, inflicting irreparable damage on the Japanese fleet.[8] Military historian John Keegan has called it "the most stunning and decisive blow in the history of naval warfare."'
    },{
        'id': '13',
        'eventID': '13',
        'start': '1942-08-07',
        'end': '1943-02-09',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Guadalcanal Campaign',
        'location': 'Guadalcanal, Solomon Islands',
        'lat': '-9.5773284',
        'lng': '160.1455805',
        'wiki': 'http://en.wikipedia.org/wiki/Guadalcanal_Campaign',
        'description': 'The Guadalcanal Campaign, also known as the Battle of Guadalcanal and codenamed Operation Watchtower by Allied forces, was fought between August 7, 1942 and February 9, 1943 on and around the island of Guadalcanal in the Pacific theatre of World War II. It was part of the Allied strategic plan to protect the convoy routes between the US, Australia and New Zealand. Launched a few months after the Kokoda Track campaign, it was the second major offensive by Allied forces against the Empire of Japan.'
    },{
        'id': '14',
        'eventID': '14',
        'start': '1942-08-23',
        'end': '1943-12-25',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Solomon Islands Campaign',
        'location': 'Solomon Islands',
        'lat': '-9.64571',
        'lng': '160.156194',
        'wiki': 'http://en.wikipedia.org/wiki/Solomon_Islands_campaign',
        'description': 'The Solomon Islands campaign was a major campaign of the Pacific War of World War II. The campaign began with Japanese landings and occupation of several areas in the British Solomon Islands and Bougainville, in the Territory of New Guinea, during the first six months of 1942. The Japanese occupied these locations and began the construction of several naval and air bases with the goals of protecting the flank of the Japanese offensive in New Guinea, establishing a security barrier for the major Japanese base at Rabaul on New Britain, and providing bases for interdicting supply lines between the Allied powers of the United States and Australia and New Zealand.'
    },{
        'id': '15',
        'eventID': '15',
        'start': '1943-03-26',
        'end': '1943-08-16',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Aleutian Islands Campaign',
        'location': 'Aleutian Islands, Alaska',
        'lat': '54.8166667',
        'lng': '-164.0333333',
        'wiki': 'http://en.wikipedia.org/wiki/Aleutian_Islands_Campaign',
        'description': 'The Aleutian Islands Campaign was a struggle over the Aleutian Islands, part of Alaska, in the Pacific campaign of World War II starting on June 3, 1942. A small Japanese force occupied the islands of Attu and Kiska, but the remoteness of the islands and the difficulties of weather and terrain meant that it took nearly a year for a large U.S. force to eject them. The islands\' strategic value was their ability to control Pacific Great Circle routes. This control of the Pacific transportation routes is why General Billy Mitchell stated to Congress in 1935 "I believe that in the future, whoever holds Alaska will hold the world. I think it is the most important strategic place in the world." The Japanese reasoned that control of the Aleutians would prevent a possible U.S. attack across the Northern Pacific. Similarly, the U.S. feared that the islands would be used as bases from which to launch aerial assaults against the West Coast.'
    },{
        'id': '16',
        'eventID': '16',
        'start': '1943-11-13',
        'end': '1944-02-21',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Gilbert and Marshall Islands campaign',
        'location': 'Marshall Islands',
        'lat': '7.131474',
        'lng': '171.184478',
        'wiki': 'http://en.wikipedia.org/wiki/Gilbert_and_Marshall_Islands_campaign',
        'description': 'In the Pacific Theater of World War II, the Gilbert and Marshall Islands campaign, from November 1943 through February 1944, were key strategic operations of the United States Navy and Marine Corps in the Central Pacific. The campaign was preceded by a raid on Makin Island by U.S. Marines in August, 1942.'
    },{
        'id': '17',
        'eventID': '17',
        'start': '1944-06-13',
        'end': '1944-08-10',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Mariana and Palau Islands campaign',
        'location': 'Mariana Islands',
        'lat': '16.6166667',
        'lng': '145.6166667',
        'wiki': 'http://en.wikipedia.org/wiki/Mariana_and_Palau_Islands_campaign',
        'description': 'The Mariana and Palau Islands campaign was an offensive launched by United States forces against Imperial Japanese forces in the Mariana Islands and Palau in the Pacific Ocean between June and November, 1944 during the Pacific War. The United States offensive, under the overall command of Chester Nimitz, followed the Gilbert and Marshall Islands campaign and was intended to neutralize Japanese bases in the central Pacific, support the Allied drive to retake the Philippines, and provide bases for a strategic bombing campaign against Japan.'
    },{
        'id': '18',
        'eventID': '18',
        'start': '1944-09-15',
        'end': '1945-06-14',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Battle of Morotai',
        'location': 'Morotai, Indonesia',
        'lat': '2.3656672',
        'lng': '128.4008357',
        'wiki': 'http://en.wikipedia.org/wiki/Battle_of_Morotai',
        'description': 'The Battle of Morotai, part of the Pacific War, began on September 15, 1944 and continued until the war ended in August 1945. The fighting began when United States and Australian forces landed on the south-west corner of Morotai, a small island in the Netherlands East Indies (NEI), which the Allies needed as a base to support the liberation of the Philippines later that year. The invading forces greatly outnumbered the island\'s Japanese defenders and secured their objectives in two weeks. Japanese reinforcements landed on the island between September and November, but lacked the supplies needed to effectively attack the Allied defensive perimeter. Intermittent fighting continued until the end of the war, with the Japanese troops suffering heavy loss of life from disease and starvation.'
    },{
        'id': '19',
        'eventID': '19',
        'start': '1944-10-02',
        'end': '1945-08-15',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Philippines Campaign',
        'location': 'Philippines',
        'lat': '16.281555',
        'lng': '121.554290',
        'wiki': 'http://en.wikipedia.org/wiki/Philippines_Campaign_(1944%E2%80%9345)',
        'description': 'The Philippines campaign of 1944–45, the Battle of the Philippines 1944–45, or the Liberation of the Philippines was the American and Filipino campaign to defeat and expel the Imperial Japanese forces occupying the Philippines, during World War II. The Japanese Army had overrun all of the Philippines during the first half of 1942. The Liberation of the Philippines commenced with a amphibious landings on the eastern Philippine island of Leyte on October 20, 1944, and hostilities in a small part of the Philippines continued through the end of the war in August 1945.'
    },{
        'id': '20',
        'eventID': '20',
        'start': '1945-02-19',
        'end': '1945-03-26',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Battle of Iwo Jima',
        'location': 'Iwo Jima',
        'lat': '24.7833333',
        'lng': '141.3166667',
        'wiki': 'http://en.wikipedia.org/wiki/Battle_of_Iwo_Jima',
        'description': 'The Battle of Iwo Jima, or Operation Detachment, was a battle in which the United States fought for and captured Iwo Jima from Japan. The U.S. invasion was charged with the mission of capturing the three airfields on Iwo Jima.[2] The battle produced some of the fiercest fighting in the Pacific Campaign of World War II.'
    },{
        'id': '21',
        'eventID': '21',
        'start': '1945-02-19',
        'end': '1945-08-10',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Bombing of Tokyo',
        'location': 'Tokyo, Japan',
        'lat': '35.6894875',
        'lng': '139.6917064',
        'wiki': 'http://en.wikipedia.org/wiki/Bombing_of_Tokyo',
        'description': 'The bombing of Tokyo by the United States Army Air Forces took place during the Pacific campaigns of World War II. The United States mounted a single spectacular raid on Tokyo in April 1942. Strategic bombing and urban area bombing began in 1944 after the long-range B-29 Super Fortress bomber entered service, first employed from China and thereafter the Mariana Islands. B-29 raids from those islands commenced on November 17, 1944 and lasted until August 15, 1945, the day Japan capitulated.[1] Out of numerous air raids on Japan\'s capital, five of which collectively destroyed over 51% of the metropolis, the so-called Great Tokyo Air Raid of 9-10 March 1945 warrants attention for being one of the most destructive bombing raids in history.'
    },{
        'id': '22',
        'eventID': '22',
        'start': '1945-04-01',
        'end': '1945-06-21',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Okinawa Campaign',
        'location': 'Okinawa, Japan',
        'lat': '26.2124013',
        'lng': '127.6809317',
        'wiki': 'http://en.wikipedia.org/wiki/Battle_of_Okinawa',
        'description': 'The Battle of Okinawa, codenamed Operation Iceberg,[3] was fought on the Ryukyu Islands of Okinawa and was the largest amphibious assault in the Pacific War.[4][5] The 82-day-long battle lasted from early April until mid-June, 1945.'
    },{
        'id': '23',
        'eventID': '23',
        'start': '1945-04-11',
        'end': '1945-08-15',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Borneo Campaign',
        'location': 'Borneo, Indonesia',
        'lat': '3.298469',
        'lng': '117.632245',
        'wiki': 'http://en.wikipedia.org/wiki/Borneo_campaign_(1945)',
        'description': 'The Borneo Campaign of 1945 was the last major Allied campaign in the South West Pacific Area, during World War II. In a series of amphibious assaults between 1 May and 21 July, the Australian I Corps, under General Leslie Morshead, attacked Japanese forces occupying the island. Allied naval and air forces, centred on the U.S. 7th Fleet under Admiral Thomas Kinkaid, the Australian First Tactical Air Force and the U.S. Thirteenth Air Force also played important roles in the campaign. They were resisted by Imperial Japanese Navy and Army forces in southern and eastern Borneo, under Vice-Admiral Michiaki Kamada, and in the north west by the Thirty-Seventh Army, led by Lieutenant-General Baba Masao.'
    },{
        'id': '24',
        'eventID': '24',
        'start': '1945-08-06',
        'end': '1945-08-09',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Atomic Bombing of Hiroshima and Nagasaki',
        'location': 'Hiroshima, Japan',
        'lat': '34.3852029',
        'lng': '132.4552927',
        'wiki': 'http://en.wikipedia.org/wiki/Atomic_bombings_of_Hiroshima_and_Nagasaki',
        'description': 'During the final stages of World War II in 1945, the United States conducted two atomic bombings against the cities of Hiroshima and Nagasaki in Japan.'
    },{
        'id': '25',
        'eventID': '25',
        'start': '1945-08-14',
        'end': '1945-09-02',
        'durationEvent' : false,
        'isDuration': 'true',
        'title': 'Japan\'s Surrender',
        'location': 'Tokyo, Japan',
        'lat': '35.5627921',
        'lng': '139.874354',
        'wiki': 'http://en.wikipedia.org/wiki/Surrender_of_Japan',
        'description': 'The surrender of Japan brought hostilities in World War II to a close. By the end of July 1945, the Imperial Japanese Navy was incapable of conducting operations and an Allied invasion of Japan was imminent. While publicly stating their intent to fight on to the bitter end, Japan\'s leaders at the Supreme Council for the Direction of the War (the "Big Six") were privately making entreaties to the neutral Soviet Union, to mediate peace on terms favorable to the Japanese. The Soviets, meanwhile, were preparing to attack the Japanese, in fulfillment of their promises to the Americans and the British made at the Tehran and Yalta Conferences.'
    }]
}