//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 

namespace Xiaonei.XmlSchema
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.xiaonei.com/1.0/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://api.xiaonei.com/1.0/", IsNullable = false)]
    public partial class users_getInfo_response
    {

        private user[] userField;

        private bool listField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("user")]
        public user[] user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://api.xiaonei.com/1.0/")]
    public partial class user
    {

        private int uidField;

        private string nameField;

        private int sexField;

        private bool sexFieldSpecified;

        private string birthdayField;

        private string tinyurlField;

        private string headurlField;

        private string mainurlField;

        private hometown_location hometown_locationField;

        private work_history work_historyField;

        private university_history university_historyField;

        private hs_history hs_historyField;

        /// <remarks/>
        public int uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public int sex
        {
            get
            {
                return this.sexField;
            }
            set
            {
                this.sexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sexSpecified
        {
            get
            {
                return this.sexFieldSpecified;
            }
            set
            {
                this.sexFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string birthday
        {
            get
            {
                return this.birthdayField;
            }
            set
            {
                this.birthdayField = value;
            }
        }

        /// <remarks/>
        public string tinyurl
        {
            get
            {
                return this.tinyurlField;
            }
            set
            {
                this.tinyurlField = value;
            }
        }

        /// <remarks/>
        public string headurl
        {
            get
            {
                return this.headurlField;
            }
            set
            {
                this.headurlField = value;
            }
        }

        /// <remarks/>
        public string mainurl
        {
            get
            {
                return this.mainurlField;
            }
            set
            {
                this.mainurlField = value;
            }
        }

        /// <remarks/>
        public hometown_location hometown_location
        {
            get
            {
                return this.hometown_locationField;
            }
            set
            {
                this.hometown_locationField = value;
            }
        }

        /// <remarks/>
        public work_history work_history
        {
            get
            {
                return this.work_historyField;
            }
            set
            {
                this.work_historyField = value;
            }
        }

        /// <remarks/>
        public university_history university_history
        {
            get
            {
                return this.university_historyField;
            }
            set
            {
                this.university_historyField = value;
            }
        }

        /// <remarks/>
        public hs_history hs_history
        {
            get
            {
                return this.hs_historyField;
            }
            set
            {
                this.hs_historyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://api.xiaonei.com/1.0/")]
    public partial class hometown_location
    {

        private string countryField;

        private string provinceField;

        private string cityField;

        /// <remarks/>
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string province
        {
            get
            {
                return this.provinceField;
            }
            set
            {
                this.provinceField = value;
            }
        }

        /// <remarks/>
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://api.xiaonei.com/1.0/")]
    public partial class friend_info
    {

        private int uid1Field;

        private int uid2Field;

        private bool are_friendsField;

        /// <remarks/>
        public int uid1
        {
            get
            {
                return this.uid1Field;
            }
            set
            {
                this.uid1Field = value;
            }
        }

        /// <remarks/>
        public int uid2
        {
            get
            {
                return this.uid2Field;
            }
            set
            {
                this.uid2Field = value;
            }
        }

        /// <remarks/>
        public bool are_friends
        {
            get
            {
                return this.are_friendsField;
            }
            set
            {
                this.are_friendsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://api.xiaonei.com/1.0/")]
    public partial class friend
    {

        private int idField;

        private string nameField;

        private string headurlField;

        /// <remarks/>
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string headurl
        {
            get
            {
                return this.headurlField;
            }
            set
            {
                this.headurlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://api.xiaonei.com/1.0/")]
    public partial class hs_info
    {

        private string nameField;

        private int grad_yearField;

        private bool grad_yearFieldSpecified;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public int grad_year
        {
            get
            {
                return this.grad_yearField;
            }
            set
            {
                this.grad_yearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grad_yearSpecified
        {
            get
            {
                return this.grad_yearFieldSpecified;
            }
            set
            {
                this.grad_yearFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://api.xiaonei.com/1.0/")]
    public partial class hs_history
    {

        private hs_info[] hs_infoField;

        private bool listField;

        private bool listFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hs_info")]
        public hs_info[] hs_info
        {
            get
            {
                return this.hs_infoField;
            }
            set
            {
                this.hs_infoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listSpecified
        {
            get
            {
                return this.listFieldSpecified;
            }
            set
            {
                this.listFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://api.xiaonei.com/1.0/")]
    public partial class university_info
    {

        private string nameField;

        private int yearField;

        private bool yearFieldSpecified;

        private string departmentField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public int year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearSpecified
        {
            get
            {
                return this.yearFieldSpecified;
            }
            set
            {
                this.yearFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://api.xiaonei.com/1.0/")]
    public partial class university_history
    {

        private university_info[] university_infoField;

        private bool listField;

        private bool listFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("university_info")]
        public university_info[] university_info
        {
            get
            {
                return this.university_infoField;
            }
            set
            {
                this.university_infoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listSpecified
        {
            get
            {
                return this.listFieldSpecified;
            }
            set
            {
                this.listFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://api.xiaonei.com/1.0/")]
    public partial class work_info
    {

        private string company_nameField;

        private string descriptionField;

        private string start_dateField;

        private string end_dateField;

        /// <remarks/>
        public string company_name
        {
            get
            {
                return this.company_nameField;
            }
            set
            {
                this.company_nameField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string start_date
        {
            get
            {
                return this.start_dateField;
            }
            set
            {
                this.start_dateField = value;
            }
        }

        /// <remarks/>
        public string end_date
        {
            get
            {
                return this.end_dateField;
            }
            set
            {
                this.end_dateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://api.xiaonei.com/1.0/")]
    public partial class work_history
    {

        private work_info[] work_infoField;

        private bool listField;

        private bool listFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("work_info")]
        public work_info[] work_info
        {
            get
            {
                return this.work_infoField;
            }
            set
            {
                this.work_infoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listSpecified
        {
            get
            {
                return this.listFieldSpecified;
            }
            set
            {
                this.listFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.xiaonei.com/1.0/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://api.xiaonei.com/1.0/", IsNullable = false)]
    public partial class users_getLoggedInUser_response
    {

        private int valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://api.xiaonei.com/1.0/")]
    [System.Xml.Serialization.XmlRootAttribute("auth_getSession_response", Namespace = "http://api.xiaonei.com/1.0/", IsNullable = false)]
    public partial class session_info
    {

        private string session_keyField;

        private int uidField;

        private string secretField;

        /// <remarks/>
        public string session_key
        {
            get
            {
                return this.session_keyField;
            }
            set
            {
                this.session_keyField = value;
            }
        }

        /// <remarks/>
        public int uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }

        /// <remarks/>
        public string secret
        {
            get
            {
                return this.secretField;
            }
            set
            {
                this.secretField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.xiaonei.com/1.0/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://api.xiaonei.com/1.0/", IsNullable = false)]
    public partial class friends_get_response
    {

        private int[] uidField;

        private bool listField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uid")]
        public int[] uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.xiaonei.com/1.0/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://api.xiaonei.com/1.0/", IsNullable = false)]
    public partial class friends_getFriends_response
    {

        private friend[] friendField;

        private bool listField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("friend")]
        public friend[] friend
        {
            get
            {
                return this.friendField;
            }
            set
            {
                this.friendField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.xiaonei.com/1.0/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://api.xiaonei.com/1.0/", IsNullable = false)]
    public partial class friends_areFriends_response
    {

        private friend_info[] friend_infoField;

        private bool listField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("friend_info")]
        public friend_info[] friend_info
        {
            get
            {
                return this.friend_infoField;
            }
            set
            {
                this.friend_infoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.xiaonei.com/1.0/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://api.xiaonei.com/1.0/", IsNullable = false)]
    public partial class friends_getAppUsers_response
    {

        private int[] uidField;

        private bool listField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uid")]
        public int[] uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.xiaonei.com/1.0/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://api.xiaonei.com/1.0/", IsNullable = false)]
    public partial class requests_sendRequest_response
    {

        private int[] uidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uid")]
        public int[] uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
    }

}